pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
            args '-u root:root'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'cd ..;mvn -B -DskipTests clean package'
            }
    }
    
 }
}
